import '@/globals.css';
import type { Metadata } from 'next';
import { Inter } from "next/font/google";
import { Providers } from './providers';
import '@rainbow-me/rainbowkit/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3253985609382295"
     crossOrigin="anonymous"></script>
     <meta name="google-adsense-account" content="ca-pub-3253985609382295"></meta>
      <body className={inter.className}>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3253985609382295"
     crossOrigin="anonymous"></script>
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
